# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sagittarius
description:      "Good artists copy,Great artist steal."
email: mavenwei@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeffreywei.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  JeffreyWei

# Assign a default image for your site's header and footer
default_bg:       http://jeffreywei.github.io/images/Clouds.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Specify the average Words per minute. If not defined, 180 will be used
wpm:              200
# Turn on or off the fin animations in the header and footer
triangleheader:  true
animated_fins:   true
# Specify the fin color in RGB value
fin_color:        "255,255,255"


# Build settings
markdown: kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "<!--more-->"

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

